[tool.poetry]
name = "shared-utils"
version = "0.1.0"
description = "Shared utility functions."
authors = ["leomosley <leo.mosley2@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "shared_utils" }]

[tool.poetry.dependencies]
python = "^3.11"
dotenv = "^0.9.9"
fastapi = "^0.115.12"
pyjwt = "^2.10.1"
pytest = "^8.3.5"


[tool.poetry.group.dev.dependencies]
requests = "^2.32.3"
pytest-asyncio = "^0.26.0"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-xml = "^0.1.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--junitxml=test-results/pytest/results.xml"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
